#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DOTSPATH=$HOME/.dotfiles
export UZDOTSROOT=$DOTSPATH/zsh-internal
export UZDOTS=${UZDOTSROOT}/zdots

export ZSOURCED=zshenv-root:$ZSOURCED


if [[ -s "${UZDOTS}/zshenv" ]]; then
	  source "$UZDOTS"/zshenv
fi
