#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


export ZELLIJ_AUTO_EXIT=true
export ZELLIJ_AUTO_ATTACH=true


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "${UZDOTS}/zshrc" ]]; then
  source "${UZDOTS}/zshrc"
fi

if [[ "$TERM_PROGRAM" == "ghostty" ]]; then
    export TERM=xterm-256color
    eval "$(zellij setup --generate-auto-start zsh)"
fi


# Execute code only if STDERR is bound to a TTY.
if [[ -o INTERACTIVE && -t 2 ]]; then
  fortune -a | cowsay -f $(ls /usr/share/cowsay/cows | shuf -n1)
  if [[ $( date +%A ) != "Friday" ]]; then echo "Its not Friday :("; else echo "Yea Friday!"; fi
fi >&2

if [[ :$PATH: != *:/etc/firecfg.py/overrides/bin:* ]]; then
    echo 'WARNING: firecfg.py in not in $PATH!'
fi
